baseurl = "/"
title = "noone.dev"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "disqus_cleverswine"

[params]
    author = "Kevin Noone"
    info = "Software Engineer in Portland, Oregon, USA"
    description = "Kevin's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "/android-chrome-192x192.png"
    favicon_32 = "/favicon-32x32.png"
    favicon_16 = "/favicon-16x16.png"
    footercontent = ""
    hidecredits = false
    hidecopyright = false
    rtl = false
    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/cleverswine/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/cleverswine/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/kevinnoone/"
[[params.social]]
    name = "Flickr"
    icon = "fab fa-flickr"
    weight = 4
    url = "http://www.flickr.com/photos/cleverswine/"    
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 5
    url = "https://myhugosite.com/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "Archive"
    weight = 3
    url  = "/archives/"
